### ISSUE TITLE
unsupported token type

### ISSUE THREAD

**Issue by michalsoczynski** [fkooman/php-oauth2-client#12]
Hi @fkooman,

According to https://tools.ietf.org/html/rfc6750#page-14 :

`HTTP Authentication Scheme(s):      Bearer`

In the file AccessToken:311 you used:

`if ('bearer' !== $tokenType) {`

I think the condition should be changed to:
`if ('bearer' !== strtolower($tokenType)) {`
or
`if ('Bearer' !== $tokenType) {`
or
`if ('Bearer' !== ucfirst($tokenType)) {`

Can you change it? or I can create a pull request if you want.

**Comment by fkooman** [comment]
Fixed in 5.0.3, thanks!
