### ISSUE TITLE
integrate with zabbix 

### ISSUE THREAD

**Issue by zhiyuazo** [fkooman/php-oauth2-client#13]
hi, fkmoon:
say hello from nokia softerware.  
we complete "zabbix integrate with keycloak" with the help from **php-oauth2-client-5.0.2** 
during this work, we do some changes on this library, list main changes below:
![image](https://user-images.githubusercontent.com/13962028/38549093-e98dea96-3ce5-11e8-96db-b409a30b3adf.png)
in your php-oauth2-client library, provide 2 method to store token 
- SessionTokenStorage.php
- PdoTokenStorage.php
zabbix have its own DB manipulations, so the above changes are focus on zabbix DB manipulate 

finally , the above changes are not general implement while it is useful for zabbix  , we suggest create a branch to store those changes, is OK?

**Comment by fkooman** [comment]
Thanks for using php-oauth2-client! :)

A few things:
1. You are free to use the library under the MIT license, so no need to ask for permission :-)
2. I don't (actively) maintain version 5 of the OAuth client since version 6 was released some time ago;
3. What changes did you make in CurlHttpClient? They may be interesting for my version as well, can you share those?
4. I indeed think it is better to create a (private) branch for your version. If you are willing you can of course contribute back changes that would also benefit other users of the OAuth client on a case-by-case basis.

Thanks again!

**Comment by CsatariGergely** [comment]
Hi (also from Nokia)

Thanks for providing php-oauth2-client! :)

Some clarification questions: 
2) Would it be okay to implement these in version 6 and do a backport to version 5?
4) Why do you propose an internal fork? Because of version 5 or because of the actual feature?

**Comment by fkooman** [comment]
> 2) Would it be okay to implement these in version 6 and do a backport to version 5?

You mean implement your changes for version 6 as well so you can upgrade?

> 4) Why do you propose an internal fork? Because of version 5 or because of the actual feature?

Because if the changes you made or only relevant for your use, then it doesn't really make sense to add them to my version of php-oauth2-client, right?

**Comment by zhiyuazo** [comment]
hi,fkooman, 
for **CurlHttpClient.php** 
i add the below snippet
![image](https://user-images.githubusercontent.com/13962028/38601982-f7b598ec-3d9b-11e8-8ef0-74fa8f036da5.png)
I know,  configure php.ini can also  make PHP service  verify the certificate of another server. 
while the above snippet handle the https/http request more freedom for zabbix.

**Comment by fkooman** [comment]
If you deploy on Debian/CentOS/RHEL/Fedora verifying the host/peer are the default. They use the built-in certificates that are trusted by the system. You are using self-signed certificates I assume? 

If not, and you can't use the system CA, I recommend using something like https://github.com/paragonie/certainty for working with up to date CA lists.

Modifying these settings can be quite dangerous! Be careful!

**Comment by zhiyuazo** [comment]
OK，thanks your comments . 
this issue can be closed. 
thanks your wonderful library ^_^
