### ISSUE TITLE
changes for  zabbix&keycloak 

### ISSUE THREAD

**Issue by zhiyuazo** [fkooman/php-oauth2-client#14]
Hi,  fkooman:
I create a branch named zk503 in nokia repo, 
please see the diff info,  would you like to maintain those changes?
if not , we will keep those in nokia repo .
I also update the README file with a short abstract for zabbix&keycloak.
Thanks , fkooman. 
AccessToken.php 

> git diff af4d0f9 33b39af  src/AccessToken.php

Provider.php 

> git diff af4d0f9 33b39af  src/Provider.php

OAuthClient.php 

> diff src/OAuthClient.php  src/OAuthClient4zk.php

sorry ,
add the link  :https://github.com/nokia/php-oauth2-client/tree/zk503

**Comment by CsatariGergely** [comment]
@fkooman ^^^

**Comment by fkooman** [comment]
Hi! 

I don't see any benefit to adding Zabbix/Keycloak support directly in php-oauth2-client. It adds a lot of code to the project that has no other use than for those specific OAuth servers.

That being said, I do see some benefit if php-oauth2-client were to be restructured to allow "addons" or "plugins" that would enable support for those providers, and ideally the NCLOC of php-oauth2-client itself would go down in that process. This would allow you to use php-oauth2-client directly while adding some additional plugin classes, like you already have for the token storage, without needing to maintain your own fork of php-oauth2-client...

Would you be interested in this?

**Comment by fkooman** [comment]
Just to be clear: I'm not making any promises of merging your code! Only if it actually improves php-oauth2-client. If all you want is a working OAuth client for you guys I'd recommend just keeping what you have and not spend any more time on it!

**Comment by zhiyuazo** [comment]
get it ,
thanks fkooman.
